## pepr parameters for RM8376
---
project_id: MG002
center: NIST
RM: RM8375-MG002
ref: /pepr-data/CFSAN030013.fasta
exp_design:
  miseq:
    - accession: SRR1979039
      plat: miseq
      vial: 0
      rep: 1
    - accession: SRR1979040
      plat: miseq
      vial: 0
      rep: 2
    - accession: SRR1979041
      plat: miseq
      vial: 1
      rep: 1
    - accession: SRR1979042
      plat: miseq
      vial: 1
      rep: 2
    - accession: SRR1979043
      plat: miseq
      vial: 2
      rep: 1
    - accession: SRR1979070
      plat: miseq
      vial: 2
      rep: 2
    - accession: SRR1979044
      plat: miseq
      vial: 3
      rep: 1
    - accession: SRR1979045
      plat: miseq
      vial: 3
      rep: 2
    - accession: SRR1979046
      plat: miseq
      vial: 4
      rep: 1
    - accession: SRR1979047
      plat: miseq
      vial: 4
      rep: 2
    - accession: SRR1979048
      plat: miseq
      vial: 5
      rep: 1
    - accession: SRR1979049
      plat: miseq
      vial: 5
      rep: 2
    - accession: SRR1979050
      plat: miseq
      vial: 6
      rep: 1
    - accession: SRR1979060
      plat: miseq
      vial: 6
      rep: 2
    - accession: SRR1979064
      plat: miseq
      vial: 7
      rep: 1
    - accession: SRR1979065
      plat: miseq
      vial: 7
      rep: 2
  pgm:
    - accession: SRR2002412
      plat: pgm
      vial: 0
      rep: 1
    - accession: SRR2002413
      plat: pgm
      vial: 1
      rep: 1
    - accession: SRR2002414
      plat: pgm
      vial: 2
      rep: 1
    - accession: SRR2002415
      plat: pgm
      vial: 3
      rep: 1
    - accession: SRR2002416
      plat: pgm
      vial: 4
      rep: 1
    - accession: SRR2002418
      plat: pgm
      vial: 5
      rep: 1
    - accession: SRR2002419
      plat: pgm
      vial: 6
      rep: 1
    - accession: SRR2002420
      plat: pgm
      vial: 7
      rep: 1
  pacbio:
    - accession: SRR2056302
      plat: pacbio
      vial: 9
      rep: 1
    - accession: SRR2056306
      plat: pacbio
      vial: 9
      rep: 2
    - accession: SRR2056310
      plat: pacbio
      vial: 9
      rep: 3
